* SSH Grimore
** Installation
*** recipe 1471207682, install with guix

$ guix pull
$ guix package -i openssh rsync sshpass sshfs-fuse

$ which ssh && ssh -V
** config

*** Config Notes

Keychain
This document describes how to use SSH shared keys along with the
keychain program. It assumes basic knowledge of public key
cryptography.
https://wiki.gentoo.org/wiki/Keychain

man 5 ssh_config

IdentityFile
...
The file name may use the tilde syntax to refer to a user's home
directory or one of the following escape characters: ‘%d’ (local
user's home directory), ‘%u’ (local user name), ‘%l’ (local host
name), ‘%h’ (remote host name) or ‘%r’ (remote user name).
...
is possible to have multiple identity files specified in configuration
files; all these identities will be tried in sequence.
*** config: 1467472232

#+NAME: config
#+BEGIN_SRC conf
	Host mail.creativedragon.local
			 ProxyCommand ssh -q -W 192.168.122.181:22 user@host.local
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/virt/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/virt/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/virt/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/virt/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/virt/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/virt/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600

	Host *.vagrant
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600

	Host github.com
			 PreferredAuthentications publickey
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/repo/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/repo/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes

	Host *
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/main/%r_%h_admin_ed25519
			 IdentityFile ~/.ssh/main/%r_%h_admin_rsa
			 IdentityFile ~/.ssh/main/%r_%h_admin_ecdsa
			 IdentityFile ~/.ssh/main/%r_%h_admin_ed25519_old
			 IdentityFile ~/.ssh/main/%r_%h_admin_rsa_old
			 IdentityFile ~/.ssh/main/%r_%h_admin_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600

#+END_SRC
*** config: 1459184671


#+NAME: config
#+BEGIN_SRC conf
	Host *.docker
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/docker/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/docker/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600

	Host *.vagrant
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600

	Host github.com
			 PreferredAuthentications publickey
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/repo/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/repo/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 # ControlMaster auto
			 # ControlPath ~/.ssh/sockets/%r@%h:%p
			 # ControlPersist 600

	Host *
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/main/%r_%h_admin_ed25519
			 IdentityFile ~/.ssh/main/%r_%h_admin_rsa
			 IdentityFile ~/.ssh/main/%r_%h_admin_ecdsa
			 IdentityFile ~/.ssh/main/%r_%h_admin_ed25519_old
			 IdentityFile ~/.ssh/main/%r_%h_admin_rsa_old
			 IdentityFile ~/.ssh/main/%r_%h_admin_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600
#+END_SRC
*** config: 1457563031

#+NAME: config
#+BEGIN_SRC conf

	Match user *docker*
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/docker/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/docker/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600

	Match user *vagrant*
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600

	Host github.com
			 PreferredAuthentications publickey
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ed25519
			 IdentityFile ~/.ssh/repo/%r_%h_dev_rsa
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ecdsa
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ed25519_old
			 IdentityFile ~/.ssh/repo/%r_%h_dev_rsa_old
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ecdsa_old
			 IdentitiesOnly yes
			 # ControlMaster auto
			 # ControlPath ~/.ssh/sockets/%r@%h:%p
			 # ControlPersist 600

	Host *
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/main/%r_%h_admin_ed25519
			 IdentityFile ~/.ssh/main/%r_%h_admin_rsa
			 IdentityFile ~/.ssh/main/%r_%h_admin_ecdsa
			 IdentityFile ~/.ssh/main/%r_%h_admin_ed25519_old
			 IdentityFile ~/.ssh/main/%r_%h_admin_rsa_old
			 IdentityFile ~/.ssh/main/%r_%h_admin_ecdsa_old
			 IdentitiesOnly yes
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p
			 ControlPersist 600
#+END_SRC

*** config: 1457540538

#+NAME: config
#+BEGIN_SRC conf
	Match user *docker*
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/docker/%r_%h_dev_ecdsa
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p

	Match user *vagrant*
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/vagrant/%r_%h_dev_ecdsa
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p

	Host github.com
			 PreferredAuthentications publickey
			 IdentityFile ~/.ssh/repo/%r_%h_dev_ecdsa
			 # ControlMaster auto
			 # ControlPath ~/.ssh/sockets/%r@%h:%p

	Host *
			 PreferredAuthentications publickey,password
			 IdentityFile ~/.ssh/main/%r_%h_admin_ecdsa
			 ControlMaster auto
			 ControlPath ~/.ssh/sockets/%r@%h:%p

#+END_SRC

** SSH Agent

*** Start ssh agent

$ eval "$(ssh-agent -s)"
*** Add a key
$ ssh-add <key-path>/<private-key>

*** Set the SSH Agent Socker Location
This allows for the sharing of an existing ssh-agent

$ export SSH_AGENT_PID=<pid>
$ export SSH_AUTH_SOCK=<path-to-socker>

Example:
export SSH_AUTH_SOCK=/tmp/ssh-et1CVxAiXx0n/agent.1453

** SSH/Key life cycle
-p port
Port to connect to on the remote host.  This can be specified on a
per-host basis in the configuration file.

*** Login to server/host

ssh-add -L
ssh-add <key-path>/<private-key> # add key if not in the agent
ssh <username>@<host> [-p <port>]
ssh-add -L

*** New ssh key

cd <key-path>
ssh-keygen -t ed25519 -f <name>_ed25519
cd ~/
ssh-add  <priviate-key-path>
ssh-add -L
# ensure there are no active connection are sockets
ssh-copy-id -i <public-key-path> [-p <port>] <username>@<remote-server>
ssh <username>@<remote-server>

*** Old ssh key

# on local server
cd <key-path>
mv -v <key> <key>_old
# see/goto new ssh key, then continue.

ssh <username>@<host> [-p <port>]
sed '/<name of file>$/d' ~/.ssh/authorized_keys
sed -i '/<name of file>$/d' ~/.ssh/authorized_keys
** SSH to a machine via another (gateway)


$ ssh -t <user1>@<gateway> ssh <user2>@<target>

Example
$ ssh -t jake@jax.local ssh user@192.168.122.181
** Disable Root Login

Step 1: Modify Configuration

$ $EDITOR /etc/ssh/sshd_config

Change the following line from
#PermitRootLogin no

to

PermitRootLogin no


Step 2: Restart SSH

restart SSH Daemon
/etc/init.d/sshd restart
or
service sshd restart

Step 3: Test Root Login

ssh root@<server>
